//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UtahPlanners.Domain
{
    public partial class Picture
    {
        public int id { get; set; }
        public Nullable<short> frontPage { get; set; }
        public Nullable<short> mainPicture { get; set; }
        public Nullable<short> secondaryPicture { get; set; }
        public byte[] binaryData { get; set; }
        public string mimeType { get; set; }
        public Nullable<int> property_id { get; set; }
    
        public virtual Property Property { get; set; }
    }
    
}
