//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UtahPlanners.Domain
{
    public partial class PropertiesIndex
    {
        public string city { get; set; }
        public int id { get; set; }
        public Nullable<int> OverallScore { get; set; }
        public string PropertyTypeDescription { get; set; }
        public Nullable<double> density { get; set; }
        public Nullable<int> units { get; set; }
        public Nullable<int> yearBuilt { get; set; }
        public string StreetTypeDescription { get; set; }
        public string StreetWalkDescription { get; set; }
        public Nullable<int> walkscore { get; set; }
        public string SocioEconDescription { get; set; }
        public Nullable<int> twoFiftySingleFam { get; set; }
    }
    
}
