//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace UtahPlanners.Domain
{
    public partial class Property
    {
        public Property()
        {
            this.Pictures = new HashSet<Picture>();
        }
    
        public int id { get; set; }
        public Nullable<int> typeCode { get; set; }
        public Nullable<double> density { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> units { get; set; }
        public Nullable<int> streetCode { get; set; }
        public Nullable<int> yearBuilt { get; set; }
        public Nullable<int> socioEcon { get; set; }
        public Nullable<int> streetSaftey { get; set; }
        public Nullable<int> buildingEnclosure { get; set; }
        public Nullable<int> commonAreas { get; set; }
        public Nullable<int> streetConn { get; set; }
        public Nullable<int> streetWalk { get; set; }
        public Nullable<int> walkscore { get; set; }
        public Nullable<int> neighCondition { get; set; }
        public Nullable<int> twoFiftySingleFam { get; set; }
        public Nullable<int> twoFiftyApts { get; set; }
        public string notes { get; set; }
        public string adminNotes { get; set; }
        public string walkscoreNotes { get; set; }
        public string notFinished { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual CommonCode CommonCode { get; set; }
        public virtual EnclosureCode EnclosureCode { get; set; }
        public virtual NeighborhoodCode NeighborhoodCode { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual StreetType StreetType { get; set; }
        public virtual SocioEconCode SocioEconCode { get; set; }
        public virtual StreetconnCode StreetconnCode { get; set; }
        public virtual StreetSafteyCode StreetSafteyCode { get; set; }
        public virtual StreetwalkCode StreetwalkCode { get; set; }
    }
    
}
