//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace UtahPlanners.Domain.Entity
{
    [DataContract]
    public partial class Address
    {
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public string street1 { get; set; }
    	[DataMember]
        public string street2 { get; set; }
    	[DataMember]
        public string city { get; set; }
    	[DataMember]
        public string state { get; set; }
    	[DataMember]
        public string zip { get; set; }
    	[DataMember]
        public string country { get; set; }
    
    	[DataMember]
        public virtual Property Property { get; set; }
    }
    
}
