//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace UtahPlanners.Domain.Entity
{
    [DataContract]
    public partial class PropertiesIndex
    {
    	[DataMember]
        public string city { get; set; }
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public Nullable<int> OverallScore { get; set; }
    	[DataMember]
        public string PropertyTypeDescription { get; set; }
    	[DataMember]
        public Nullable<double> density { get; set; }
    	[DataMember]
        public Nullable<int> units { get; set; }
    	[DataMember]
        public Nullable<int> yearBuilt { get; set; }
    	[DataMember]
        public string StreetTypeDescription { get; set; }
    	[DataMember]
        public string StreetWalkDescription { get; set; }
    	[DataMember]
        public Nullable<int> walkscore { get; set; }
    	[DataMember]
        public string SocioEconDescription { get; set; }
    	[DataMember]
        public Nullable<int> twoFiftySingleFam { get; set; }
    }
    
}
