//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace UtahPlanners.Domain.Entity
{
    [DataContract]
    public partial class StreetType
    {
        public StreetType()
        {
            this.Properties = new HashSet<Property>();
        }
    
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public string description { get; set; }
    
    	[DataMember]
        public virtual ICollection<Property> Properties { get; set; }
    }
    
}
