//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace UtahPlanners.Domain.Entity
{
    [DataContract(IsReference = true)]
    public partial class Weight
    {
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public Nullable<int> streetWalk { get; set; }
    	[DataMember]
        public Nullable<int> walkscore { get; set; }
    	[DataMember]
        public Nullable<int> twoFiftySingleFam { get; set; }
    	[DataMember]
        public Nullable<int> buildingEnclosure { get; set; }
    	[DataMember]
        public Nullable<int> streetConn { get; set; }
    	[DataMember]
        public Nullable<int> commonAreas { get; set; }
    	[DataMember]
        public Nullable<int> streetSaftey { get; set; }
    	[DataMember]
        public Nullable<int> neighCondition { get; set; }
    	[DataMember]
        public Nullable<int> twoFiftyApts { get; set; }
    }
    
}
